### ISSUE TITLE
error for `pip install pytrec_eval`

### ISSUE THREAD

**Issue by mechsihao** [cvangysel/pytrec_eval#54]
Hi~, I met a error when I install pytrec_eval with pip3

my env is linux, which python version is `python3.10`, and pip is alse upgrade to latest, idon't known why~
```
Processing ./pytrec_eval-0.5.tar.gz
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "/usr/lib/python3.10/http/client.py", line 1283, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
          self.send(msg)
        File "/usr/lib/python3.10/http/client.py", line 976, in send
          self.connect()
        File "/usr/lib/python3.10/http/client.py", line 1455, in connect
          self.sock = self._context.wrap_socket(self.sock,
        File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
          return self.sslsocket_class._create(
        File "/usr/lib/python3.10/ssl.py", line 1071, in _create
          self.do_handshake()
        File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-o24w6fkg/setup.py", line 27, in <module>
          response = urllib.request.urlopen(REMOTE_TREC_EVAL_URI)
        File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
          return opener.open(url, data, timeout)
        File "/usr/lib/python3.10/urllib/request.py", line 519, in open
          response = self._open(req, data)
        File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
          result = func(*args)
        File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>
      Fetching trec_eval from https://github.com/usnistgov/trec_eval/archive/v9.0.8.tar.gz.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tferracina** [comment]
I have the same issue.

**Comment by GasolSun36** [comment]
I have the same issue but I solved, here is the solution:

the main reason is that you have problem with connect to github.com, so first we need to `wget` download though the url: [https://mirrors.ustc.edu.cn/pypi/packages/2e/03/e6e84df6a7c1265579ab26bbe30ff7f8c22745aa77e0799bba471c0a3a19/pytrec_eval-0.5.tar.gz](https://mirrors.ustc.edu.cn/pypi/packages/2e/03/e6e84df6a7c1265579ab26bbe30ff7f8c22745aa77e0799bba471c0a3a19/pytrec_eval-0.5.tar.gz)

Then, `tar -xzvf pytrec_eval-0.5.tar.gz` and cd to `pytrec_eval-0.5`, and also `wget` the trec_eval-9.0.8.tar.gz:
[https://codeload.github.com/usnistgov/trec_eval/tar.gz/refs/tags/v9.0.8](https://codeload.github.com/usnistgov/trec_eval/tar.gz/refs/tags/v9.0.8)

Next, change the variable in `setup.py`:

`REMOTE_TREC_EVAL_URI = 'file:///path/to/your/trec_eval-9.0.8.tar.gz'`

Then, install by `python setup.py install`.

**Comment by Moriiikdt** [comment]
@GasolSun36  Thanks for your answer !

But just change the `REMOTE_TREC_EVAL_URI` variable maybe not enough , I untar the trec_eval-9.0.8.tar.gz to the pytrec_eval-0.5 path , then change the  `setup.py` code :

```
import os
import sys
import tempfile

from setuptools import setup, Extension

# Project root directory
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
# Local extracted trec_eval directory (if you have pre-extracted)
LOCAL_TREC_EVAL_DIR = os.path.join(ROOT_DIR, 'trec_eval-9.0.8')
# Local archive file
LOCAL_TREC_EVAL_ARCHIVE = os.path.join(ROOT_DIR, 'trec_eval-9.0.8.tar.gz')
# Remote fallback URL
REMOTE_TREC_EVAL_URI = 'https://github.com/usnistgov/trec_eval/archive/v9.0.8.tar.gz'
# Expected top-level folder name inside archive
REMOTE_TREC_EVAL_TLD_NAME = 'trec_eval-9.0.8'

# Prepare source list
TREC_EVAL_SRC = []

with tempfile.TemporaryDirectory() as tmp_dir:
    # 1) Use pre-extracted local directory if available
    if os.path.isdir(LOCAL_TREC_EVAL_DIR) and os.path.isfile(os.path.join(LOCAL_TREC_EVAL_DIR, 'trec_eval.h')):
        print(f'Using local trec_eval directory: {LOCAL_TREC_EVAL_DIR}')
        trec_eval_dir = LOCAL_TREC_EVAL_DIR
    # 2) Extract from local archive if present
    elif os.path.isfile(LOCAL_TREC_EVAL_ARCHIVE):
        print(f'Extracting trec_eval from local archive: {LOCAL_TREC_EVAL_ARCHIVE}')
        if LOCAL_TREC_EVAL_ARCHIVE.endswith('.zip'):
            import zipfile
            trec_eval_archive = zipfile.ZipFile(LOCAL_TREC_EVAL_ARCHIVE)
        else:
            import tarfile
            trec_eval_archive = tarfile.open(LOCAL_TREC_EVAL_ARCHIVE, mode='r:gz')
        trec_eval_archive.extractall(tmp_dir)
        trec_eval_dir = os.path.join(tmp_dir, REMOTE_TREC_EVAL_TLD_NAME)
    # 3) Fallback: download remotely
    else:
        print(f'Fetching trec_eval from remote URI: {REMOTE_TREC_EVAL_URI}')
        import io
        import urllib.request
        response = urllib.request.urlopen(REMOTE_TREC_EVAL_URI)
        mmap_f = io.BytesIO(response.read())
        if REMOTE_TREC_EVAL_URI.endswith('.zip'):
            import zipfile
            trec_eval_archive = zipfile.ZipFile(mmap_f)
        else:
            import tarfile
            trec_eval_archive = tarfile.open(fileobj=mmap_f, mode='r:*')
        trec_eval_archive.extractall(tmp_dir)
        trec_eval_dir = os.path.join(tmp_dir, REMOTE_TREC_EVAL_TLD_NAME)

    # Collect all .c sources except trec_eval.c
    for fname in os.listdir(trec_eval_dir):
        if fname.endswith('.c') and fname != 'trec_eval.c':
            TREC_EVAL_SRC.append(os.path.join(trec_eval_dir, fname))
    # On Windows include windows subdir
    if sys.platform == 'win32':
        win_dir = os.path.join(trec_eval_dir, 'windows')
        if os.path.isdir(win_dir):
            for fname in os.listdir(win_dir):
                if fname.endswith('.c') and fname != 'trec_eval.c':
                    TREC_EVAL_SRC.append(os.path.join(win_dir, fname))

    # Build extension
    pytrec_eval_ext = Extension(
        'pytrec_eval_ext',
        sources=['src/pytrec_eval.cpp'] + TREC_EVAL_SRC,
        libraries=[] if sys.platform == 'win32' else ['m', 'stdc++'],
        include_dirs=[trec_eval_dir] + ([os.path.join(trec_eval_dir, 'windows')] if sys.platform == 'win32' else []),
        undef_macros=['NDEBUG'],
        extra_compile_args=['-g', '-Wall', '-O3'],
        define_macros=[
            ('VERSIONID', '"pytrec_eval"'),
            ('_GLIBCXX_USE_CXX11_ABI', '0'),
            ('P_NEEDS_GNU_CXX_NAMESPACE', '1')
        ]
    )

# Final setup
setup(
    name='pytrec_eval',
    version='0.5',
    description='Provides Python bindings for popular Information Retrieval measures implemented within trec_eval.',
    author='Christophe Van Gysel',
    author_email='cvangysel@uva.nl',
    ext_modules=[pytrec_eval_ext],
    packages=['pytrec_eval'],
    package_dir={'pytrec_eval': 'py'},
    python_requires='>=3',
    url='https://github.com/cvangysel/pytrec_eval',
    download_url='https://github.com/cvangysel/pytrec_eval/tarball/0.5',
    keywords=[
        'trec_eval',
        'information retrieval',
        'evaluation',
        'ranking',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python',
        'Programming Language :: C++',
        'Intended Audience :: Science/Research',
        'Operating System :: POSIX :: Linux',
        'Topic :: Text Processing :: General',
    ]
)

```
Then, install by `pip install . ` 

This approach should perfectly resolve the issue.
